name: ${COMPOSE_PROJECT_NAME:-ingversionsdigital-live-stage}

services:
  web:
    container_name: ${CONTAINER_NAME:-ingversionsdigital-live-stage}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: staging
    image: ingversionsdigital-live:stage
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME:-ingversionsdigital-live-stage}.rule=Host(`${WEBSITE_DOMAIN:-staging.ingversionsdigital.com}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME:-ingversionsdigital-live-stage}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME:-ingversionsdigital-live-stage}.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME:-ingversionsdigital-live-stage}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME:-ingversionsdigital-live-stage}.service=${TRAEFIK_SERVICE_NAME:-ingversionsdigital-live-stage}"
      - "traefik.http.services.${TRAEFIK_SERVICE_NAME:-ingversionsdigital-live-stage}.loadbalancer.server.port=80"
    ports:
      - "${WEBSITE_PUBLIC_PORT:-8091}:80"

networks:
  default:
    name: ${DOCKER_NETWORK_NAME:-ingversionsdigital-live-stage-network}
